#ifndef _ASMARM_BOOTFB_H
#define _ASMARM_BOOTFB_H

#define FONT_WIDTH 8
#define FONT_HEIGHT 8
#define FONT_CHAR_SHIFT 3
#define FONT_STRUCT_DATA_OFFSET 16

#define FB_CHARS_WIDTH (CONFIG_DEBUG_BOOTFB_WIDTH / FONT_WIDTH)
#define FB_CHARS_HEIGHT (CONFIG_DEBUG_BOOTFB_HEIGHT / FONT_HEIGHT)

#define LINE_END (FB_CHARS_WIDTH * FONT_WIDTH * CONFIG_DEBUG_BOOTFB_PIXEL_SIZE)
#define LINE_SKIP (CONFIG_DEBUG_BOOTFB_STRIDE - LINE_END)

#define BOOTFB_SIZE (CONFIG_DEBUG_BOOTFB_STRIDE * FB_CHARS_HEIGHT * FONT_HEIGHT - LINE_SKIP)
#define BOOTFB_LEN PAGE_ALIGN(BOOTFB_SIZE + 4 + (CONFIG_DEBUG_BOOTFB_PHYS & ~PAGE_MASK))

#ifndef __ASSEMBLY__

extern void *bootfb_addr;
extern int bootfb_skip_for_pageinit;

#endif /* !__ASSEMBLY__ */

#endif /* _ASMARM_BOOTFB_H */
